version: '3.3'

services:
    reactjs:
        container_name: reactjs
        build:
            context: ./reactjs
            dockerfile: Dockerfile
            args:
                buildno: 1
        networks:
            clusternetwork:
                ipv4_address: 172.16.0.15
        ports:
            - "8889:8889"
        volumes:
            - "$PWD/reactjs:/app"
            - "/app/myexample/node_modules"
    nodejs:
        build:
            context: ./nodejs
            dockerfile: Dockerfile
            args:
                buildno: 1
        container_name: nodejs
        networks:
            clusternetwork:
                ipv4_address: 172.16.0.14
        ports:
            - "443:443"
            - "1337:1337"
            - "8888:8888"
        depends_on:
            - reactjs
        volumes:
            - "$PWD/nodejs/app:/app"
            - "/app/node_modules"
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
            args:
                buildno: 1
        container_name: nginx
        networks:
            clusternetwork:
                ipv4_address: 172.16.0.16
        ports:
            - "80:80"
            - "1338:1338"
            - "33333:33333"
        depends_on:
            - reactjs
            - nodejs
networks:
    clusternetwork:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.16.0.0/24
