version: '3.3'

services:
    reactjs:
        container_name: reactjs
        build:
            context: ./reactjs
            dockerfile: Dockerfile
            args:
                buildno: 1
        ports:
            - "8889:8889"
        volumes:
            - "$PWD/reactjs:/app"
            - "/app/myexample/node_modules"
        networks:
            - our_net
    nodejs:
        build:
            context: ./nodejs
            dockerfile: Dockerfile
            args:
                buildno: 1
        container_name: nodejs
        ports:
            - "443:443"
            - "1337:1337"
            - "8888:8888"
        depends_on:
            - reactjs
        volumes:
            - "$PWD/nodejs/app:/app"
            - "$PWD/nodejs/mysql:/var/lib/mysql"
            - "/app/node_modules"
        networks:
            - our_net
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
            args:
                buildno: 1
        container_name: nginx
        ports:
            - "80:80"
            - "1338:1338"
            - "33333:33333"
        depends_on:
            - reactjs
            - nodejs
        networks:
            - our_net
networks:
    our_net:
        driver: bridge
